apiVersion: v1
kind: Service
metadata:
  name: httpd-loadbalancer
  namespace: httpd
  labels:
    app: httpd
spec:
  type: LoadBalancer
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30002