apiVersion: v1
kind: Service
metadata:
  name: httpd-nodeport
  labels:
    app: httpd
spec:
  type: NodePort
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30000