apiVersion: v1
kind: Namespace
metadata:  
  labels:
    kubernetes.io/metadata.name: tunnels
  name: tunnels 
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-forward
  namespace: tunnels
  labels:
    app: httpd-forward
spec:
  replicas: 2
  selector:    
    matchLabels:
      app: httpd-forward
  template:
    metadata:
      labels:
        app: httpd-forward
    spec:
      containers:
        - name: httpd
          image: tsemach/httpd
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-forward
  namespace: tunnels    
  labels:
    app: httpd-forward
spec:
  type: LoadBalancer
  selector:
    app: httpd-forward
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30003
