apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  namespace: httpd
  labels:
    app: httpd
spec:
  replicas: 2
  selector:    
    matchLabels:
      app: httpd    
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: tsemach/httpd
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service  
  namespace: httpd
  labels:
    app: httpd
spec:
  type: NodePort
  selector:
    app: httpd

  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30001
          