apiVersion: v1
kind: Namespace
metadata:  
  labels:
    kubernetes.io/metadata.name: httpd
  name: httpd  
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  namespace: httpd
  labels:
    app: httpd
spec:
  replicas: 2
  selector:    
    matchLabels:
      app: httpd    
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: tsemach/httpd
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-loadbalancer
  namespace: httpd
  labels:
    app: httpd
  # annotations:
  #   metallb.universe.tf/loadBalancerIPs: 192.168.1.100
spec:
  type: LoadBalancer
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30002