apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  namespace: minio
  labels:
    type: minio-pv
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.122.1
    path: "/shared/k8s.share/minio"
  

