apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-deployment
  namespace: cluster
  labels:
    app: nestjs
spec:
  replicas: 2
  selector:    
    matchLabels:
      app: nestjs
  template:
    metadata:
      labels:
        app: nestjs
    spec:
      containers:
        - name: nestjs
          image: 192.168.122.1:5000/nestjs
          ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nestjs-service  
  namespace: cluster
  labels:
    app: nestjs
spec:
  type: LoadBalancer
  selector:
    app: nestjs

  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
      nodePort: 30005
          