apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-deployment
  namespace: cluster
  labels:
    app: nestjs
spec:
  replicas: 2
  selector:    
    matchLabels:
      app: nestjs
  template:
    metadata:
      labels:
        app: nesdtjs
    spec:
      containers:
        - name: nestjs
          image: 192.168.122.1:5000/nestjs
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 1Gi
              cpu: "0.5"
            requests:
              memory: 512Mi
              cpu: "0.2"          
---
apiVersion: v1
kind: Service
metadata:
  name: nestjs-service  
  namespace: cluster
  labels:
    app: nestjs
spec:
  # type: LoadBalancer
  # type: ExternalName
  # externalName: nestjs-service.cluster.svc.cluster.local
  selector:
    app: nestjs

  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      # nodePort: 30005
          