apiVersion: v1
kind: Service
metadata:
  name: posgres-nodeport-service
  namespace: postgres
  labels:
    app: postgres
spec:
  type: NodePort  
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30100
