apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-test
spec:
  storageClassName: mongodb-nfs-storageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
