apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: jenkins
---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-token
  annotations:
    kubernetes.io/service-account.name: jenkins
type: kubernetes.io/service-account-token