apiVersion: v1
kind: Pod
metadata:
  name: nginx-node-selector
  namespace: scheduling
spec:
  containers:
  - name: nginx
    image: nginx
  # comment node-1 with label type=cpu so nodeSelector will select those nodes
  # kubectl label node node-1 type=cpu
  nodeSelector:
    type: cpu
