apiVersion: v1
kind: Pod
metadata:
  name: bosybox-with-affinity
  namespace: scheduling
spec:
  containers:
  - name: pod-affinity
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
              - linux
      preferredDuringSchedulingIgnoredDuringExecution:    
      - weight: 1
        preference:
          # node-2 hase lable of target=node-2 
          # kubectl label node node-2 target=node-2
          matchExpressions:
            - key: target
              operator: In
              values:
              - node-2