apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx  
spec:
  ingressClassName: nginx
  rules:
    - host: nginx.tsemach.org
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nginx-service
              port:
                number: 8080        
  