apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-deployment
  namespace: cluster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stress-deployment
  template:
    metadata:
      labels:
        app: stress-deployment
    spec:
      containers:
      - name: stress-deployment
        image: ubuntu
        command: ["/bin/sh", "-c", "apt-get update && apt-get install -y stress-ng && while true; do stress-ng --cpu 1; done"]
        resources:
          limits:
            cpu: 1m
            memory: 10Mi
          requests:
            cpu: 1m
            memory: 10Mi
            