apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-deployment
  namespace: cluster
  labels:
    app: nestjs
spec:
  replicas: 2
  selector:    
    matchLabels:
      app: nestjs
  template:
    metadata:
      labels:
        app: nestjs
    spec:
      containers:
        - name: nestjs
          image: 192.168.122.1:5000/nestjs
          ports:
            - containerPort: 3000
          env:
            {{- range $key, $value := .Values.environment.values }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $value := .Values.environment.configmap }}
            - name: {{ $key }}              
              valueFrom:
                configMapKeyRef:
                  name: nestjs-configmap
                  # key: {{ $value | quote }}
                  key: {{ $value }}
            {{- end }}
            {{- range $key, $value := .Values.environment.secret }}
            - name: {{ $key }}              
              valueFrom:
                secretKeyRef:
                  name: nestjs-secret
                  # key: {{ $value | quote }}
                  key: {{ $value }}
            {{- end }}            
          resources:
            limits:
              memory: 1Gi
              cpu: "0.5"
            requests:
              memory: 512Mi
              cpu: "0.2"