apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-deployment
  namespace: cluster
  labels:
    app: nestjs
spec:
  replicas: 2
  selector:    
    matchLabels:
      app: nestjs
  template:
    metadata:
      labels:
        app: nestjs
    spec:
      containers:
        - name: nestjs
          image: 192.168.122.1:5000/nestjs
          ports:
            - containerPort: 3000
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapRef:
                  name: nestjs-configmap
                  key: POSTGRES_HOST                  
            - name: POSTGRES_PORT
              valueFrom:
                configMapRef:
                  name: nestjs-configmap
                  key: POSTGRES_PORT                  
            - name: POSTGRES_USERNAME
              valueFrom:
                secretMapRef:
                  name: nestjs-secret
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretMapRef:
                  name: nestjs-secret
                  key: POSTGRES_PASSWORD
          resources:
            limits:
              memory: 1Gi
              cpu: "0.5"
            requests:
              memory: 512Mi
              cpu: "0.2"