apiVersion: v1
kind: Service
metadata:
  name: nestjs-service  
  namespace: cluster
  labels:
    app: nestjs
spec:
  # type: LoadBalancer
  # type: ExternalName
  # externalName: nestjs-service.cluster.svc.cluster.local
  selector:
    app: nestjs

  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      # nodePort: 30005
